image: python:3.12-bullseye

lint:
  stage: build
  script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install black
    - black --check .
