image: python:3.12-bullseye

lint:
  stage: build
  script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install black
    - black --check .

test:
  script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python setup.py test
    - pip install tox flake8
    - tox -e py,flake8
